language: python
python:
  - "2.7"
# Building 3.3 fails;
# ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions
# have backported the necessary changes to older versions).
#  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  # force six to install first as it's a dependicy of simplegeneric and simplegeneric is erroring.
  - pip install six
  - pip install jupyter
  - pip install pdfkit
  - pip install -e .
# command to run tests
script:
  - jupyter nbextension install --py hide_code --sys-prefix
  - jupyter nbextension enable --py hide_code --sys-prefix
  - jupyter serverextension enable --py hide_code --sys-prefix
