language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install jupyter
  - pip install pdfkit
# command to run tests
script: 
  - jupyter nbextension install --py hide_code --sys-prefix
  - jupyter nbextension enable --py hide_code --sys-prefix
  - juypter serverextension enable -py hide_code --sys-prefix
